CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'brand',
    created_at TEXT DEFAULT (CURRENT_TIMESTAMP::TEXT)
);
CREATE TABLE IF NOT EXISTS creators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    handle TEXT UNIQUE NOT NULL,
    platform TEXT DEFAULT 'Instagram',
    followers BIGINT NOT NULL DEFAULT 0,
    engagement DOUBLE PRECISION NOT NULL DEFAULT 0,
    niche TEXT DEFAULT '',
    city TEXT DEFAULT '',
    trust_score INTEGER DEFAULT 70,
    completed_collaborations INTEGER DEFAULT 0,
    successful_posts INTEGER DEFAULT 0,
    ghosted_campaigns INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT DEFAULT '',
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    description TEXT DEFAULT '',
    reserved_units INTEGER DEFAULT 0,
    shipped_units INTEGER DEFAULT 0,
    unit_cost DOUBLE PRECISION DEFAULT 0
);
CREATE TABLE IF NOT EXISTS campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT REFERENCES users(id),
    title TEXT NOT NULL,
    product_id BIGINT REFERENCES products(id),
    niche TEXT DEFAULT '',
    city TEXT DEFAULT '',
    budget DOUBLE PRECISION DEFAULT 0,
    status TEXT DEFAULT 'active',
    created_at TEXT DEFAULT (CURRENT_TIMESTAMP::TEXT),
    description TEXT DEFAULT '',
    minimum_followers BIGINT DEFAULT 0,
    minimum_engagement DOUBLE PRECISION DEFAULT 0,
    posting_deadline_days INTEGER DEFAULT 7,
    target_platform TEXT DEFAULT 'Instagram',
    deliverables TEXT DEFAULT '1 social post'
);
CREATE TABLE IF NOT EXISTS collaborations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT REFERENCES campaigns(id),
    creator_id BIGINT REFERENCES creators(id),
    status TEXT DEFAULT 'invited',
    agreed_value DOUBLE PRECISION DEFAULT 0,
    created_at TEXT DEFAULT (CURRENT_TIMESTAMP::TEXT),
    claimed_at TEXT,
    shipped_at TEXT,
    delivered_at TEXT,
    deadline TEXT,
    completed_at TEXT
);
CREATE TABLE IF NOT EXISTS shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collaboration_id BIGINT REFERENCES collaborations(id),
    provider TEXT DEFAULT 'Mock',
    tracking_code TEXT,
    stage TEXT DEFAULT 'order_placed',
    updated_at TEXT DEFAULT (CURRENT_TIMESTAMP::TEXT),
    dispatched_at TEXT,
    delivered_at TEXT
);
CREATE TABLE IF NOT EXISTS proofs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collaboration_id BIGINT REFERENCES collaborations(id),
    url TEXT NOT NULL UNIQUE,
    caption TEXT DEFAULT '',
    verified INTEGER DEFAULT 0,
    submitted_at TEXT DEFAULT (CURRENT_TIMESTAMP::TEXT),
    verified_by BIGINT REFERENCES users(id),
    verified_at TEXT
);
CREATE TABLE IF NOT EXISTS trust_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT REFERENCES creators(id),
    event_type TEXT NOT NULL,
    score_change INTEGER NOT NULL,
    reason TEXT DEFAULT '',
    created_at TEXT DEFAULT (CURRENT_TIMESTAMP::TEXT)
);
CREATE INDEX IF NOT EXISTS idx_creators_niche ON creators(niche);
CREATE INDEX IF NOT EXISTS idx_campaign_status ON campaigns(status);
CREATE INDEX IF NOT EXISTS idx_collab_status ON collaborations(status);
CREATE INDEX IF NOT EXISTS idx_shipments_collab ON shipments(collaboration_id);
